= Quickstart
Swarmlab
:idprefix:
:idseparator: -
:!example-caption:
:!table-caption:
:page-pagination:
  

This is where your wondeful journey in the vast world of Swarmlab begins.

== Senario 1

* you are a *teacher* and want to prepare your lesson 
** create exercises and examples
** share them with your students
* you are a *student* and want to try your newly acquired knowledge on some project
* you are a *Developer* and would like to denug your application or a real world senario
** you want to provide POC
* you are a *user* and just want to try out stuff
** you want to play around with examples but are too scared to do so on your system

Well this is where you start!

=== start service
=== start storage 
=== start labroom


== Senario 2

You have already completed senario 1 (using swarmlab or you own resources) and would now like to collaborate with others.
* as a teacher you would like to distribute the lesson you have prepared and work on it throughout the semester
* as a developer you want to coordinate with your team
* as a student you want to communicate and cooperate with your friends

Lets begin!

=== create network
=== invite
=== share
==== app
==== volume


